name: Build Typst document
on:
  push:
    branches:
      - main

jobs:
  build_typst_documents:
    runs-on: ubuntu-latest
    steps:
      - name: Install Ipaexfont
        run: sudo apt-get install -y fonts-ipaexfont

      - name: Checkout
        uses: actions/checkout@v4

      - name: Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: main.typ

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: main.pdf
          path: main.pdf
  release:
    needs: build_typst_documents
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download PDF
        uses: actions/download-artifact@v4
        with:
          name: main.pdf

      - name: Release
        id: create_release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          publish: true

      - name: Upload PDF
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: main.pdf
